version: '3.8'

services:
    dev:
        container_name: nestjs-reading-detector
        image: nestjs-reading-detector:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:read